osx_image: xcode10.2
language: objective-c
sudo: false
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  matrix:
    - WORKSPACE="MDC-101/ObjectiveC/Starter/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-101/ObjectiveC/Complete/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-101/ObjectiveC/Starter/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-101/ObjectiveC/Complete/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-102/ObjectiveC/Starter/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-102/ObjectiveC/Complete/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-102/ObjectiveC/Starter/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-102/ObjectiveC/Complete/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-103/ObjectiveC/Starter/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-103/ObjectiveC/Complete/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-103/ObjectiveC/Starter/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-103/ObjectiveC/Complete/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-104/ObjectiveC/Starter/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-104/ObjectiveC/Complete/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-104/ObjectiveC/Starter/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-104/ObjectiveC/Complete/Shrine/Shrine.xcworkspace" SCHEME="Shrine" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-111/ObjectiveC/Starter/MDC-111.xcworkspace" SCHEME="MDC-111" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-111/ObjectiveC/Complete/MDC-111.xcworkspace" SCHEME="MDC-111" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-111/ObjectiveC/Starter/MDC-111.xcworkspace" SCHEME="MDC-111" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"
    - WORKSPACE="MDC-111/ObjectiveC/Complete/MDC-111.xcworkspace" SCHEME="MDC-111" DESTINATION="OS=12.0,name=iPhone XS" SDK="iphonesimulator12.0"

before_install:
  - gem install cocoapods xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination="$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO EXPANDED_CODE_SIGN_IDENTITY="-" EXPANDED_CODE_SIGN_IDENTITY_NAME="-" | xcpretty -c;
